### ISSUE TITLE
Version 2025.0.3 is not open source?

### ISSUE THREAD

**Issue by ricaun** [Nice3point/RevitToolkit#12]
I was planning to do a PR and noticed the version difference from the nuget and this repository.

I wonder the reason of that, and what changed between version `2025.0.2` and `2025.0.3`.

![image](https://github.com/user-attachments/assets/d7777949-4c7d-44b5-bd01-60d456ecfea1)

![image](https://github.com/user-attachments/assets/e3d3ee03-dd4b-4951-a635-d957f1efeaad)

**Comment by Nice3point** [comment]
https://github.com/Nice3point/RevitToolkit/blob/main/Changelog.md#release-202503

2025.0.3 Minor fix related to removal of unused dependency. The develop branch is usually up to date always

The release will be published in the main branch in a few minutes, sorry for its unavailability

**Comment by Nice3point** [comment]
I didn't do automatic publishing on Nuget because of high risks of invalid versions or accidental pushes to the main branch. And not wanting to frequently update token in Github secrets for all Open source projects.  Nuget package cannot be removed, only hidden, so it is much more convenient and reliable to build and remove outdated versions locally. If the project becomes more global, I will reconsider this behavior

**Comment by ricaun** [comment]
> I didn't do automatic publishing on Nuget because of high risks of invalid versions or accidental pushes to the main branch. And not wanting to frequently update token in Github secrets for all Open source projects. Nuget package cannot be removed, only hidden, so it is much more convenient and reliable to build and remove outdated versions locally. If the project becomes more global, I will reconsider this behavior

I found out recently you can remove from the Nuget, but you cannot replace the version if you remove. Go in the `Contact Support` in your package and there is a option for that.

In my case I can only update the main branch by creating a PR and approving, after the Github action build everything with tests in some cases.
